// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.22.2";

// src/lib/mcp/tools/list-blog-posts.ts
import { createClient } from "npm:@supabase/supabase-js@^2.91.0";
import { defineTool } from "npm:@lovable.dev/mcp-js@0.22.2";
import { z } from "npm:zod@^4.4.3";
function supabaseForUser(ctx) {
  return createClient(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_PUBLISHABLE_KEY,
    {
      global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
      auth: { persistSession: false, autoRefreshToken: false }
    }
  );
}
var list_blog_posts_default = defineTool({
  name: "list_blog_posts",
  title: "Lister les articles de blog",
  description: "Liste les articles du blog Ecosense visibles pour l'utilisateur connect\xE9 (publi\xE9s, ou tous les articles si l'utilisateur est administrateur).",
  inputSchema: {
    status: z.enum(["published", "draft", "all"]).optional().describe("Filtrer par statut. 'all' r\xE9serv\xE9 aux administrateurs."),
    limit: z.number().int().min(1).max(100).optional().describe("Nombre maximum d'articles \xE0 retourner (d\xE9faut 20).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ status, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return {
        content: [{ type: "text", text: "Non authentifi\xE9." }],
        isError: true
      };
    }
    const supabase = supabaseForUser(ctx);
    let query = supabase.from("blog_posts").select("id, slug, title, excerpt, category, status, published_at, created_at").order("created_at", { ascending: false }).limit(limit ?? 20);
    if (!status || status === "published") {
      query = query.eq("status", "published");
    } else if (status === "draft") {
      query = query.eq("status", "draft");
    }
    const { data, error } = await query;
    if (error) {
      return {
        content: [{ type: "text", text: error.message }],
        isError: true
      };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { posts: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/get-blog-post.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.91.0";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.22.2";
import { z as z2 } from "npm:zod@^4.4.3";
function supabaseForUser2(ctx) {
  return createClient2(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_PUBLISHABLE_KEY,
    {
      global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
      auth: { persistSession: false, autoRefreshToken: false }
    }
  );
}
var get_blog_post_default = defineTool2({
  name: "get_blog_post",
  title: "R\xE9cup\xE9rer un article de blog",
  description: "R\xE9cup\xE8re le contenu complet d'un article de blog Ecosense \xE0 partir de son slug.",
  inputSchema: {
    slug: z2.string().min(1).describe("Slug unique de l'article.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ slug }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return {
        content: [{ type: "text", text: "Non authentifi\xE9." }],
        isError: true
      };
    }
    const { data, error } = await supabaseForUser2(ctx).from("blog_posts").select("*").eq("slug", slug).maybeSingle();
    if (error) {
      return {
        content: [{ type: "text", text: error.message }],
        isError: true
      };
    }
    if (!data) {
      return {
        content: [{ type: "text", text: `Aucun article trouv\xE9 pour le slug "${slug}".` }],
        isError: true
      };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { post: data }
    };
  }
});

// src/lib/mcp/tools/create-contact-message.ts
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.91.0";
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.22.2";
import { z as z3 } from "npm:zod@^4.4.3";
function supabaseForUser3(ctx) {
  return createClient3(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_PUBLISHABLE_KEY,
    {
      global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
      auth: { persistSession: false, autoRefreshToken: false }
    }
  );
}
var create_contact_message_default = defineTool3({
  name: "create_contact_message",
  title: "Envoyer un message de contact",
  description: "Enregistre un nouveau message de contact pour Ecosense Solutions (nom, email, sujet, message).",
  inputSchema: {
    name: z3.string().trim().min(1).max(200),
    email: z3.string().trim().email(),
    subject: z3.string().trim().max(300).optional(),
    message: z3.string().trim().min(1).max(5e3)
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  handler: async ({ name, email, subject, message }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return {
        content: [{ type: "text", text: "Non authentifi\xE9." }],
        isError: true
      };
    }
    const { data, error } = await supabaseForUser3(ctx).from("contact_messages").insert({ name, email, subject: subject ?? null, message }).select().maybeSingle();
    if (error) {
      return {
        content: [{ type: "text", text: error.message }],
        isError: true
      };
    }
    return {
      content: [
        {
          type: "text",
          text: `Message enregistr\xE9 (id: ${data?.id ?? "?"}).`
        }
      ],
      structuredContent: { message: data }
    };
  }
});

// src/lib/mcp/tools/list-contact-messages.ts
import { createClient as createClient4 } from "npm:@supabase/supabase-js@^2.91.0";
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.22.2";
import { z as z4 } from "npm:zod@^4.4.3";
function supabaseForUser4(ctx) {
  return createClient4(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_PUBLISHABLE_KEY,
    {
      global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
      auth: { persistSession: false, autoRefreshToken: false }
    }
  );
}
var list_contact_messages_default = defineTool4({
  name: "list_contact_messages",
  title: "Lister les messages de contact",
  description: "Liste les messages de contact re\xE7us. R\xE9serv\xE9 aux administrateurs (contr\xF4l\xE9 par les politiques RLS).",
  inputSchema: {
    status: z4.string().optional().describe("Filtrer par statut (ex: 'unread')."),
    limit: z4.number().int().min(1).max(200).optional()
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ status, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return {
        content: [{ type: "text", text: "Non authentifi\xE9." }],
        isError: true
      };
    }
    let query = supabaseForUser4(ctx).from("contact_messages").select("*").order("created_at", { ascending: false }).limit(limit ?? 50);
    if (status) query = query.eq("status", status);
    const { data, error } = await query;
    if (error) {
      return {
        content: [{ type: "text", text: error.message }],
        isError: true
      };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { messages: data ?? [] }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "imggqlzlsvbqjnabracc";
var mcp_default = defineMcp({
  name: "ecosense-mcp",
  title: "Ecosense Solutions",
  version: "0.1.0",
  instructions: "Outils Ecosense Solutions : consulter les articles du blog, envoyer un message de contact, et \u2014 pour les administrateurs \u2014 consulter les messages re\xE7us. Toutes les actions s'ex\xE9cutent au nom de l'utilisateur connect\xE9 (RLS appliqu\xE9e).",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [list_blog_posts_default, get_blog_post_default, create_contact_message_default, list_contact_messages_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.22.2/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
